### ISSUE TITLE
Use hex values for colors

### ISSUE THREAD

**Issue by AdamTillou** [CD3/tex2im#11]
There doesn't seem to be a way to use hex values as the text or background color, only predefined color names.

**Comment by CD3** [comment]
The color options are just forwarded directly to the `\color` command of latex color package

https://ctan.org/pkg/color?lang=en

I suppose this could be updated to xcolor, which I believe supports hex.

**Comment by CD3** [comment]
I just tagged a version `2.2` that uses xcolor instead of color and supports using the xcolor "modes". To do hex, you would
```
tex2im '\nabla \phi = -\vec{E}' --text-color HTML:FF7F00 
```

**Comment by AdamTillou** [comment]
Thanks for this feature, it works great!
