### ISSUE TITLE
[Feature] Output to stdout

### ISSUE THREAD

**Issue by Geronymos** [CD3/tex2im#12]
It would be nice to have an option to print the image to stdout to use it with other programs (e.g. directly open it in an image viewer, save to clipboard, ...). 

With the program is it is, it is a pain to achieve this functionality. 
```sh
tex2im "a^2 + b^2 = c^2"; cat out.png | my_app; rm out.png
```

Maybe implement that `tex2im -o -` or `tex2im` without any options prints to stdout. And if a user would want a image named _-,png_ one could write `tex2im -o "-"` or maybe `tex2im -o \-`. 

I really enjoy your program and use it to chat about math on messengers that don't support LaTeX-formulars out of the box.

**Comment by CD3** [comment]
Thank you for the comment and sorry for the delay, I did not see this until now.

I just pushed some new commits that implement this by adding a `--stdout` option. So, in your example, you should be able to do this now

```
tex2im "a^2 + b^2 = c^2" --stdout  | my_app
```

The commits are on `master` and tagged `2.3`.

Thanks again.
