### ISSUE TITLE
The -o option not working as intended

### ISSUE THREAD

**Issue by Xunius** [CD3/tex2im#6]
Hi,

I downloaded tex2im and noticed that the `-o` command line option is not working. Here is the command I issued:

```
tex2im/tex2im -r 150x150 -o ./tmp_tttt /tmp/tmp_latex_LmpBvs.tex 
```

The output image is saved to the current working directory with the name `tmp_latex_LmpBvs.png`.

I had an older version of tex2im (v1.8), the old version worked. So could it be that some changes you made broke the `-o` option?

**Comment by CD3** [comment]
Hi,

Thank you for using `tex2im` and reporting the issue. I can confirm that the `-o` option is not working in the latest 2.0.1 release. I rewrote the version 2.0 in python, and it looks like the `-o` option was broke then.

I think I have a fix implemented on the master branch, so I'll prepare a bugfix release and push it soon.

**Comment by CD3** [comment]
`-o` is working again. See 22940426232b48f68191f6c7701d3d000d5f92a6.
